language: C

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenmpi-dev openmpi-bin

install:
  - sudo make install


before_script:
  - make examples

script:
  - ./run-funnel-serial
  - mpirun -np 2 ./run-funnel-parallel

after_script:
  - make clean_examples
